//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nvn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhmuc_SP
    {
        public string MaSP { get; set; }
        public string Ten_SP { get; set; }
        public string Gia_SP { get; set; }
    
        public virtual San_Pham San_Pham { get; set; }
        public virtual San_Pham San_Pham1 { get; set; }
    }
}
